/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : string,
  'action' : string,
  'userId' : Principal,
  'role' : HospitalRole,
  'entityId' : string,
  'timestamp' : bigint,
  'entityType' : string,
}
export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'doctorId' : string,
  'patientId' : string,
  'date' : string,
  'createdBy' : Principal,
  'time' : string,
  'notes' : string,
  'reason' : string,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface Bill {
  'id' : string,
  'paymentStatus' : PaymentStatus,
  'patientId' : string,
  'createdAt' : bigint,
  'gstPercent' : number,
  'gstAmount' : number,
  'totalAmount' : number,
  'items' : Array<BillItem>,
  'appointmentId' : string,
  'subtotal' : number,
}
export interface BillItem { 'description' : string, 'amount' : number }
export interface DashboardStats {
  'pendingBillsTotal' : number,
  'totalPatients' : bigint,
  'recentActivityCount' : bigint,
  'cancelledAppointments' : bigint,
  'totalDoctors' : bigint,
  'completedAppointments' : bigint,
  'scheduledAppointments' : bigint,
  'lowStockItemsCount' : bigint,
}
export interface Doctor {
  'id' : string,
  'name' : string,
  'email' : string,
  'available' : boolean,
  'specialization' : string,
  'phone' : string,
  'registeredAt' : bigint,
}
export type HospitalRole = { 'admin' : null } |
  { 'doctor' : null } |
  { 'nurse' : null } |
  { 'pharmacist' : null } |
  { 'receptionist' : null };
export interface InventoryItem {
  'id' : string,
  'expiryDate' : string,
  'name' : string,
  'unit' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : number,
  'reorderLevel' : bigint,
}
export interface Medicine {
  'duration' : string,
  'dosage' : string,
  'name' : string,
}
export interface Patient {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'createdBy' : Principal,
  'email' : string,
  'medicalHistory' : string,
  'bloodGroup' : string,
  'address' : string,
  'gender' : string,
  'phone' : string,
  'registeredAt' : bigint,
}
export type PaymentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Prescription {
  'id' : string,
  'doctorId' : string,
  'patientId' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'notes' : string,
  'medicines' : Array<Medicine>,
  'appointmentId' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : HospitalRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivityLog' : ActorMethod<[ActivityLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[Appointment], undefined>,
  'createBill' : ActorMethod<[Bill], undefined>,
  'createDoctor' : ActorMethod<[Doctor], undefined>,
  'createInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'createPatient' : ActorMethod<[Patient], undefined>,
  'createPrescription' : ActorMethod<[Prescription], undefined>,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteBill' : ActorMethod<[string], undefined>,
  'deleteDoctor' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'deletePrescription' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getAppointment' : ActorMethod<[string], Appointment>,
  'getAppointmentsByDoctor' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByPatient' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByStatus' : ActorMethod<
    [AppointmentStatus],
    Array<Appointment>
  >,
  'getBill' : ActorMethod<[string], Bill>,
  'getBillsByPatient' : ActorMethod<[string], Array<Bill>>,
  'getBillsByPaymentStatus' : ActorMethod<[PaymentStatus], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDoctor' : ActorMethod<[string], Doctor>,
  'getInventoryItem' : ActorMethod<[string], InventoryItem>,
  'getLogsByUser' : ActorMethod<[Principal], Array<ActivityLog>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getPatient' : ActorMethod<[string], Patient>,
  'getPrescription' : ActorMethod<[string], Prescription>,
  'getPrescriptionsByDoctor' : ActorMethod<[string], Array<Prescription>>,
  'getPrescriptionsByPatient' : ActorMethod<[string], Array<Prescription>>,
  'getRecentLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointment' : ActorMethod<[string, Appointment], undefined>,
  'updateBill' : ActorMethod<[string, Bill], undefined>,
  'updateDoctor' : ActorMethod<[string, Doctor], undefined>,
  'updateInventoryItem' : ActorMethod<[string, InventoryItem], undefined>,
  'updatePatient' : ActorMethod<[string, Patient], undefined>,
  'updatePrescription' : ActorMethod<[string, Prescription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];