/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HospitalRole = IDL.Variant({
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'nurse' : IDL.Null,
  'pharmacist' : IDL.Null,
  'receptionist' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : HospitalRole,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'entityType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Text,
  'patientId' : IDL.Text,
  'date' : IDL.Text,
  'createdBy' : IDL.Principal,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'reason' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const BillItem = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Bill = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'gstPercent' : IDL.Float64,
  'gstAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(BillItem),
  'appointmentId' : IDL.Text,
  'subtotal' : IDL.Float64,
});
export const Doctor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'available' : IDL.Bool,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'expiryDate' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'reorderLevel' : IDL.Nat,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
});
export const Medicine = IDL.Record({
  'duration' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
});
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'doctorId' : IDL.Text,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'notes' : IDL.Text,
  'medicines' : IDL.Vec(Medicine),
  'appointmentId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : HospitalRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingBillsTotal' : IDL.Float64,
  'totalPatients' : IDL.Nat,
  'recentActivityCount' : IDL.Nat,
  'cancelledAppointments' : IDL.Nat,
  'totalDoctors' : IDL.Nat,
  'completedAppointments' : IDL.Nat,
  'scheduledAppointments' : IDL.Nat,
  'lowStockItemsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivityLog' : IDL.Func([ActivityLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [], []),
  'createBill' : IDL.Func([Bill], [], []),
  'createDoctor' : IDL.Func([Doctor], [], []),
  'createInventoryItem' : IDL.Func([InventoryItem], [], []),
  'createPatient' : IDL.Func([Patient], [], []),
  'createPrescription' : IDL.Func([Prescription], [], []),
  'deleteAppointment' : IDL.Func([IDL.Text], [], []),
  'deleteBill' : IDL.Func([IDL.Text], [], []),
  'deleteDoctor' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'deletePrescription' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
  'getAppointmentsByDoctor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByStatus' : IDL.Func(
      [AppointmentStatus],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getBill' : IDL.Func([IDL.Text], [Bill], ['query']),
  'getBillsByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
  'getBillsByPaymentStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Bill)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
  'getLogsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'getPrescription' : IDL.Func([IDL.Text], [Prescription], ['query']),
  'getPrescriptionsByDoctor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getPrescriptionsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Prescription)],
      ['query'],
    ),
  'getRecentLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'updateBill' : IDL.Func([IDL.Text, Bill], [], []),
  'updateDoctor' : IDL.Func([IDL.Text, Doctor], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
  'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
  'updatePrescription' : IDL.Func([IDL.Text, Prescription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HospitalRole = IDL.Variant({
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'nurse' : IDL.Null,
    'pharmacist' : IDL.Null,
    'receptionist' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : HospitalRole,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'entityType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Text,
    'patientId' : IDL.Text,
    'date' : IDL.Text,
    'createdBy' : IDL.Principal,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'reason' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const BillItem = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Bill = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'gstPercent' : IDL.Float64,
    'gstAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(BillItem),
    'appointmentId' : IDL.Text,
    'subtotal' : IDL.Float64,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'available' : IDL.Bool,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'expiryDate' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'reorderLevel' : IDL.Nat,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
  });
  const Medicine = IDL.Record({
    'duration' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'doctorId' : IDL.Text,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'notes' : IDL.Text,
    'medicines' : IDL.Vec(Medicine),
    'appointmentId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : HospitalRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingBillsTotal' : IDL.Float64,
    'totalPatients' : IDL.Nat,
    'recentActivityCount' : IDL.Nat,
    'cancelledAppointments' : IDL.Nat,
    'totalDoctors' : IDL.Nat,
    'completedAppointments' : IDL.Nat,
    'scheduledAppointments' : IDL.Nat,
    'lowStockItemsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivityLog' : IDL.Func([ActivityLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [], []),
    'createBill' : IDL.Func([Bill], [], []),
    'createDoctor' : IDL.Func([Doctor], [], []),
    'createInventoryItem' : IDL.Func([InventoryItem], [], []),
    'createPatient' : IDL.Func([Patient], [], []),
    'createPrescription' : IDL.Func([Prescription], [], []),
    'deleteAppointment' : IDL.Func([IDL.Text], [], []),
    'deleteBill' : IDL.Func([IDL.Text], [], []),
    'deleteDoctor' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'deletePrescription' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getAppointment' : IDL.Func([IDL.Text], [Appointment], ['query']),
    'getAppointmentsByDoctor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByStatus' : IDL.Func(
        [AppointmentStatus],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getBill' : IDL.Func([IDL.Text], [Bill], ['query']),
    'getBillsByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Bill)], ['query']),
    'getBillsByPaymentStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Bill)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDoctor' : IDL.Func([IDL.Text], [Doctor], ['query']),
    'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
    'getLogsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'getPrescription' : IDL.Func([IDL.Text], [Prescription], ['query']),
    'getPrescriptionsByDoctor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getPrescriptionsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Prescription)],
        ['query'],
      ),
    'getRecentLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'updateBill' : IDL.Func([IDL.Text, Bill], [], []),
    'updateDoctor' : IDL.Func([IDL.Text, Doctor], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
    'updatePatient' : IDL.Func([IDL.Text, Patient], [], []),
    'updatePrescription' : IDL.Func([IDL.Text, Prescription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };