/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BillItem {
    description: string;
    amount: number;
}
export interface ActivityLog {
    id: string;
    action: string;
    userId: Principal;
    role: HospitalRole;
    entityId: string;
    timestamp: bigint;
    entityType: string;
}
export interface DashboardStats {
    pendingBillsTotal: number;
    totalPatients: bigint;
    recentActivityCount: bigint;
    cancelledAppointments: bigint;
    totalDoctors: bigint;
    completedAppointments: bigint;
    scheduledAppointments: bigint;
    lowStockItemsCount: bigint;
}
export interface Patient {
    id: string;
    age: bigint;
    name: string;
    createdBy: Principal;
    email: string;
    medicalHistory: string;
    bloodGroup: string;
    address: string;
    gender: string;
    phone: string;
    registeredAt: bigint;
}
export interface InventoryItem {
    id: string;
    expiryDate: string;
    name: string;
    unit: string;
    quantity: bigint;
    category: string;
    price: number;
    reorderLevel: bigint;
}
export interface Bill {
    id: string;
    paymentStatus: PaymentStatus;
    patientId: string;
    createdAt: bigint;
    gstPercent: number;
    gstAmount: number;
    totalAmount: number;
    items: Array<BillItem>;
    appointmentId: string;
    subtotal: number;
}
export interface Medicine {
    duration: string;
    dosage: string;
    name: string;
}
export interface Doctor {
    id: string;
    name: string;
    email: string;
    available: boolean;
    specialization: string;
    phone: string;
    registeredAt: bigint;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    doctorId: string;
    patientId: string;
    date: string;
    createdBy: Principal;
    time: string;
    notes: string;
    reason: string;
}
export interface Prescription {
    id: string;
    doctorId: string;
    patientId: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    medicines: Array<Medicine>;
    appointmentId: string;
}
export interface UserProfile {
    name: string;
    role: HospitalRole;
    email: string;
    phone: string;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum HospitalRole {
    admin = "admin",
    doctor = "doctor",
    nurse = "nurse",
    pharmacist = "pharmacist",
    receptionist = "receptionist"
}
export enum PaymentStatus {
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addActivityLog(log: ActivityLog): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(appt: Appointment): Promise<void>;
    createBill(bill: Bill): Promise<void>;
    createDoctor(doctor: Doctor): Promise<void>;
    createInventoryItem(item: InventoryItem): Promise<void>;
    createPatient(patient: Patient): Promise<void>;
    createPrescription(prescription: Prescription): Promise<void>;
    deleteAppointment(id: string): Promise<void>;
    deleteBill(id: string): Promise<void>;
    deleteDoctor(id: string): Promise<void>;
    deleteInventoryItem(id: string): Promise<void>;
    deletePatient(id: string): Promise<void>;
    deletePrescription(id: string): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllBills(): Promise<Array<Bill>>;
    getAllDoctors(): Promise<Array<Doctor>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllPrescriptions(): Promise<Array<Prescription>>;
    getAppointment(id: string): Promise<Appointment>;
    getAppointmentsByDoctor(doctorId: string): Promise<Array<Appointment>>;
    getAppointmentsByPatient(patientId: string): Promise<Array<Appointment>>;
    getAppointmentsByStatus(status: AppointmentStatus): Promise<Array<Appointment>>;
    getBill(id: string): Promise<Bill>;
    getBillsByPatient(patientId: string): Promise<Array<Bill>>;
    getBillsByPaymentStatus(status: PaymentStatus): Promise<Array<Bill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDoctor(id: string): Promise<Doctor>;
    getInventoryItem(id: string): Promise<InventoryItem>;
    getLogsByUser(userId: Principal): Promise<Array<ActivityLog>>;
    getLowStockItems(): Promise<Array<InventoryItem>>;
    getPatient(id: string): Promise<Patient>;
    getPrescription(id: string): Promise<Prescription>;
    getPrescriptionsByDoctor(doctorId: string): Promise<Array<Prescription>>;
    getPrescriptionsByPatient(patientId: string): Promise<Array<Prescription>>;
    getRecentLogs(): Promise<Array<ActivityLog>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAppointment(id: string, updatedAppt: Appointment): Promise<void>;
    updateBill(id: string, updatedBill: Bill): Promise<void>;
    updateDoctor(id: string, updatedDoctor: Doctor): Promise<void>;
    updateInventoryItem(id: string, updatedItem: InventoryItem): Promise<void>;
    updatePatient(id: string, updatedPatient: Patient): Promise<void>;
    updatePrescription(id: string, updatedPrescription: Prescription): Promise<void>;
}
import type { ActivityLog as _ActivityLog, Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Bill as _Bill, BillItem as _BillItem, HospitalRole as _HospitalRole, PaymentStatus as _PaymentStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addActivityLog(arg0: ActivityLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivityLog(to_candid_ActivityLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivityLog(to_candid_ActivityLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_Appointment_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_Appointment_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createBill(arg0: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(to_candid_Bill_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(to_candid_Bill_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDoctor(arg0: Doctor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(arg0);
            return result;
        }
    }
    async createInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0);
            return result;
        }
    }
    async createPatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0);
            return result;
        }
    }
    async createPrescription(arg0: Prescription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0);
            return result;
        }
    }
    async deleteAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteBill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteDoctor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePrescription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrescription(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return result;
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAllPrescriptions(): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrescriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrescriptions();
            return result;
        }
    }
    async getAppointment(arg0: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_Appointment_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_Appointment_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByDoctor(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDoctor(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDoctor(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByPatient(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPatient(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPatient(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByStatus(arg0: AppointmentStatus): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByStatus(to_candid_AppointmentStatus_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBill(arg0: string): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_Bill_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_Bill_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillsByPatient(arg0: string): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsByPatient(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsByPatient(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBillsByPaymentStatus(arg0: PaymentStatus): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillsByPaymentStatus(to_candid_PaymentStatus_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillsByPaymentStatus(to_candid_PaymentStatus_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDoctor(arg0: string): Promise<Doctor> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return result;
        }
    }
    async getInventoryItem(arg0: string): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return result;
        }
    }
    async getLogsByUser(arg0: Principal): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByUser(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByUser(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return result;
        }
    }
    async getPatient(arg0: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async getPrescription(arg0: string): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescription(arg0);
            return result;
        }
    }
    async getPrescriptionsByDoctor(arg0: string): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByDoctor(arg0);
            return result;
        }
    }
    async getPrescriptionsByPatient(arg0: string): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptionsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptionsByPatient(arg0);
            return result;
        }
    }
    async getRecentLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentLogs();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentLogs();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAppointment(arg0: string, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBill(arg0: string, arg1: Bill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(arg0, to_candid_Bill_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(arg0, to_candid_Bill_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDoctor(arg0: string, arg1: Doctor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1);
            return result;
        }
    }
    async updateInventoryItem(arg0: string, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: string, arg1: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1);
            return result;
        }
    }
    async updatePrescription(arg0: string, arg1: Prescription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescription(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ActivityLog_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLog): ActivityLog {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Bill_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_HospitalRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HospitalRole): HospitalRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    doctorId: string;
    patientId: string;
    date: string;
    createdBy: Principal;
    time: string;
    notes: string;
    reason: string;
}): {
    id: string;
    status: AppointmentStatus;
    doctorId: string;
    patientId: string;
    date: string;
    createdBy: Principal;
    time: string;
    notes: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n18(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdBy: value.createdBy,
        time: value.time,
        notes: value.notes,
        reason: value.reason
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentStatus: _PaymentStatus;
    patientId: string;
    createdAt: bigint;
    gstPercent: number;
    gstAmount: number;
    totalAmount: number;
    items: Array<_BillItem>;
    appointmentId: string;
    subtotal: number;
}): {
    id: string;
    paymentStatus: PaymentStatus;
    patientId: string;
    createdAt: bigint;
    gstPercent: number;
    gstAmount: number;
    totalAmount: number;
    items: Array<BillItem>;
    appointmentId: string;
    subtotal: number;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n23(_uploadFile, _downloadFile, value.paymentStatus),
        patientId: value.patientId,
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        items: value.items,
        appointmentId: value.appointmentId,
        subtotal: value.subtotal
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _HospitalRole;
    email: string;
    phone: string;
}): {
    name: string;
    role: HospitalRole;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_HospitalRole_n28(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    userId: Principal;
    role: _HospitalRole;
    entityId: string;
    timestamp: bigint;
    entityType: string;
}): {
    id: string;
    action: string;
    userId: Principal;
    role: HospitalRole;
    entityId: string;
    timestamp: bigint;
    entityType: string;
} {
    return {
        id: value.id,
        action: value.action,
        userId: value.userId,
        role: from_candid_HospitalRole_n28(_uploadFile, _downloadFile, value.role),
        entityId: value.entityId,
        timestamp: value.timestamp,
        entityType: value.entityType
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "cancelled" in value ? PaymentStatus.cancelled : "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    doctor: null;
} | {
    nurse: null;
} | {
    pharmacist: null;
} | {
    receptionist: null;
}): HospitalRole {
    return "admin" in value ? HospitalRole.admin : "doctor" in value ? HospitalRole.doctor : "nurse" in value ? HospitalRole.nurse : "pharmacist" in value ? HospitalRole.pharmacist : "receptionist" in value ? HospitalRole.receptionist : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLog>): Array<ActivityLog> {
    return value.map((x)=>from_candid_ActivityLog_n33(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLog): _ActivityLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Bill_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Bill): _Bill {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_HospitalRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalRole): _HospitalRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    paymentStatus: PaymentStatus;
    patientId: string;
    createdAt: bigint;
    gstPercent: number;
    gstAmount: number;
    totalAmount: number;
    items: Array<BillItem>;
    appointmentId: string;
    subtotal: number;
}): {
    id: string;
    paymentStatus: _PaymentStatus;
    patientId: string;
    createdAt: bigint;
    gstPercent: number;
    gstAmount: number;
    totalAmount: number;
    items: Array<_BillItem>;
    appointmentId: string;
    subtotal: number;
} {
    return {
        id: value.id,
        paymentStatus: to_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.paymentStatus),
        patientId: value.patientId,
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        items: value.items,
        appointmentId: value.appointmentId,
        subtotal: value.subtotal
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    action: string;
    userId: Principal;
    role: HospitalRole;
    entityId: string;
    timestamp: bigint;
    entityType: string;
}): {
    id: string;
    action: string;
    userId: Principal;
    role: _HospitalRole;
    entityId: string;
    timestamp: bigint;
    entityType: string;
} {
    return {
        id: value.id,
        action: value.action,
        userId: value.userId,
        role: to_candid_HospitalRole_n3(_uploadFile, _downloadFile, value.role),
        entityId: value.entityId,
        timestamp: value.timestamp,
        entityType: value.entityType
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: HospitalRole;
    email: string;
    phone: string;
}): {
    name: string;
    role: _HospitalRole;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_HospitalRole_n3(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AppointmentStatus;
    doctorId: string;
    patientId: string;
    date: string;
    createdBy: Principal;
    time: string;
    notes: string;
    reason: string;
}): {
    id: string;
    status: _AppointmentStatus;
    doctorId: string;
    patientId: string;
    date: string;
    createdBy: Principal;
    time: string;
    notes: string;
    reason: string;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n9(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdBy: value.createdBy,
        time: value.time,
        notes: value.notes,
        reason: value.reason
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == AppointmentStatus.scheduled ? {
        scheduled: null
    } : value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} {
    return value == PaymentStatus.cancelled ? {
        cancelled: null
    } : value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HospitalRole): {
    admin: null;
} | {
    doctor: null;
} | {
    nurse: null;
} | {
    pharmacist: null;
} | {
    receptionist: null;
} {
    return value == HospitalRole.admin ? {
        admin: null
    } : value == HospitalRole.doctor ? {
        doctor: null
    } : value == HospitalRole.nurse ? {
        nurse: null
    } : value == HospitalRole.pharmacist ? {
        pharmacist: null
    } : value == HospitalRole.receptionist ? {
        receptionist: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
